// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAFpZDP2ryQ-o55McZhWZY2YdPDYK2kbWI',
//     appId: '1:956037832020:web:1f6149b5eb5274dc6ebcc1',
//     messagingSenderId: '956037832020',
//     projectId: 'acharya-habba',
//     authDomain: 'acharya-habba.firebaseapp.com',
//     storageBucket: 'acharya-habba.firebasestorage.app',
//     measurementId: 'G-E5VRDQ2WCM',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDGVZ6GYgMIbDO8mQOQw8pd6kA8Cd1jXUE',
//     appId: '1:956037832020:android:a023cbc1f5d042126ebcc1',
//     messagingSenderId: '956037832020',
//     projectId: 'acharya-habba',
//     storageBucket: 'acharya-habba.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBiheEVLcrhftSG2T8qVS2K812X4sjs0Rk',
//     appId: '1:956037832020:ios:c06999f79b7788d36ebcc1',
//     messagingSenderId: '956037832020',
//     projectId: 'acharya-habba',
//     storageBucket: 'acharya-habba.firebasestorage.app',
//     iosBundleId: 'com.ait.acharyahabba22',
//   );

// }
