name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  font_awesome_flutter: ^10.8.0
  go_router: ^14.7.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.19.0
  math_expressions: ^2.6.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  ticket_widget: ^1.0.2
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
